### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by MatteoRagni** [msiniscalchi/atom-latextools#21]
[Enter steps to reproduce below:]

Just after atom was opened. I'm only reporting the issue. In those days I have no time to investigate further...

**Atom Version**: 1.4.0
**System**: "Arch Linux"
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package, v0.7.4

### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /home/nirvana1289/.atom/packages/latextools/lib/completion-manager.coffee:32

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at CompletionManager.module.exports.CompletionManager.refCiteComplete (/home/nirvana1289/.atom/packages/latextools/lib/completion-manager.coffee:32:23)
    at /home/nirvana1289/.atom/packages/latextools/lib/latextools.coffee:216:28
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1321:25
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "markdown-preview"
    ],
    "projectHome": "/home/nirvana1289/workspace",
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  },
  "latextools": {
    "builderSettings": {},
    "darwin": {},
    "linux": {
      "atomExecutable": "atom",
      "python2": "python2.7"
    },
    "win32": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v1.0.5
emmet, v2.4.0
figlet, v0.5.3
file-icons, v1.6.14
language-arduino, v0.4.1
language-bison, v1.0.0
language-latex, v0.6.1
language-lex-flex, v0.1.0
latextools, v0.7.4
markdown-preview-plus, v2.2.2
mathjax-wrapper, v0.1.0
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-selection, v4.3.1
pdf-view, v0.39.0
preview-inline, v0.5.1

# Dev
No dev packages
```

**Comment by msiniscalchi** [comment]
Fixed in master (thanks to @ig0774 ).

**Comment by MatteoRagni** [comment]
I'm still having some issues...
Error is raised if I open Atom and the first tab is the Settings tab. It does not raise an error if tab shows a non-latex file.

**Comment by ig0774** [comment]
It's been fixed in master, which means the fix will be available in the next release.

**Comment by MatteoRagni** [comment]
Uh sorry. My ignorance in releasing for atom package. Thanks...

2016-01-25 18:11 GMT+01:00 ig0774 <notifications@github.com>:

> It's been fixed in master, which means the fix will be available in the
> next release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msiniscalchi/atom-latextools/issues/21#issuecomment-174589160>
> .
>



-- 
best regards,
MR

**Comment by msiniscalchi** [comment]
No worries @MatteoRagni. The next release is good to go, but I wanted to add a draft of the "user manual." Hopefully in a couple of days...
