### ISSUE TITLE
biblatex: \parencite, \textcite does not list references

### ISSUE THREAD

**Issue by chbuschmann** [msiniscalchi/atom-latextools#39]
The usual biblatex commands does not seem to fetch references in .bib.

**Comment by omnifocal** [comment]
This. I, and many others I'm sure, would be very grateful for the addition of biblatex citation support.

Unfortunately the level of regex hacking that appears to be required is beyond me!

**Comment by ig0774** [comment]
For the Python version, I came up with [this monstrosity](https://github.com/ig0774/LaTeXTools/blob/extended_cite_command_matching/latex_cite_completions.py#L27) which supports all the various citation commands from biblatex, natbib, csquotes, and apacite. Hasn't been merged into the Python version yet, however, because I keep hoping there's a better way.

**Comment by PaulEcoffet** [comment]
Wouldn't it be okay to just to an exhaustive list of cite commands for bibtex, biblatex and natbib and allow the user to add theirs if needed? There aren't that many cite commands.

**Comment by ig0774** [comment]
This should be fixed in v0.8.1.

**Comment by PaulEcoffet** [comment]
The issue is not fixed for biblatex. `\citep` and `\citet` are indeed working for natbib, but `\parencite` and `\textcite` do not trigger the ref panel.

**Comment by ig0774** [comment]
@PaulEcoffet: I don't know what to tell you... They certainly work for me with v0.8.1. Can you provide more detail (are you just typing, e.g. `\parencite` followed by the `{` key? Are you using either of the optional arguments, etc.?

**Comment by PaulEcoffet** [comment]
I have found the issue, it is because `{` does not trigger the
latextools:cite-keypress. I guess it is because i have to type `alt-y` to
type a { on my keyboard and it is linked with the issue #98 . I was able to
make it works with citep last time apparently but I am no longer able to.
If I type `\parencite{,`, then the comma triggers the menu. I'll use the
module you recommanded me in #98 to make my `{` working.
